# Generated by Django 4.1.3 on 2022-12-05 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("restaurant", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="menu",
            name="image",
            field=models.ImageField(blank=True, upload_to="menu_items/"),
        ),
    ]
